# Generated by Django 4.1.7 on 2023-03-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storyimage_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, to='core.user'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
