# Generated by Django 4.1.7 on 2023-03-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='follow',
        ),
    ]
