# Generated by Django 4.1.7 on 2023-03-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_viewed_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='viewed_stories',
        ),
    ]
