# Generated by Django 4.1.7 on 2023-03-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
