# Generated by Django 4.1.7 on 2023-03-15 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_menu_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
