# Generated by Django 4.1.7 on 2023-03-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_menu_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='area',
        ),
    ]
