# Generated by Django 4.1.7 on 2023-03-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_menu_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
            preserve_default=False,
        ),
    ]
