# Generated by Django 4.1.7 on 2023-03-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_menu_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=5000)),
                ('items_price', models.IntegerField(default=0)),
                ('delivery_price', models.IntegerField(default=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('order_status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PROCESSING', 'PROCESSING'), ('PACKED', 'PACKED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED')], max_length=100)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING')], max_length=100)),
                ('tx_id', models.CharField(max_length=5000)),
                ('tx_msg', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
