# Generated by Django 4.1.7 on 2023-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_orderitemquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_charge',
            field=models.IntegerField(default=20),
        ),
    ]
