# Generated by Django 4.1.7 on 2023-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_area_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
