# Generated by Django 4.1.7 on 2023-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tx_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tx_msg',
            new_name='signature',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('created', 'created'), ('attempted', 'attempted'), ('paid', 'paid')], max_length=100),
        ),
    ]
