# Generated by Django 4.1.7 on 2023-03-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_tx_id_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='Lunch', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemquantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='core.order'),
        ),
    ]
