# Generated by Django 4.1.7 on 2023-03-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcmtoken',
            field=models.CharField(default='fasdf', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='ENTER NAME', max_length=100),
        ),
    ]
