# Generated by Django 4.1.7 on 2023-03-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_fcmtoken_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PROCESSING', 'PROCESSING'), ('PACKED', 'PACKED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED')], default='ACCEPTED', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', models.TextField(max_length=1000)),
                ('seen', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_set', to='core.user')),
            ],
        ),
    ]
